%% rentals.m
% Track July revenue of a car rental company's 3 locations
% Author: Len Pieroni
% No assistance

%% Parameters

% [compact, full-sized, van, SUV]

cost = [25, 38, 53, 72];
daysRented = [250, 150, 180, 86;... % Airport location
    160, 44, 60, 20;... % Campus location
    210, 112, 120, 78]; % Elkhart location

%% Calculations

revenue = daysRented.*cost; % matrix of revenue by location and rental type

locDaysRented = [0; 0; 0]; % Days rented per location
locRevenue = [0; 0; 0]; % Revenue per location

totalDays = 0;
totalRevenue = 0;

locDaysRented = sum(daysRented, 2);
locRevenue = sum(revenue, 2);

totalDays = sum(locDaysRented);
totalRevenue = sum(locRevenue);

%% Output

out = "Airport: "...
        + num2str(locDaysRented(1))...
        + " days, $"...
        + num2str(locRevenue(1))...
        + char(10)...
    + "Campus: "...
        + num2str(locDaysRented(2))...
        + " days, $"...
        + num2str(locRevenue(2))...
        + char(10)...
    + "Elkhorn: "...
        + num2str(locDaysRented(3))...
        + " days, $"...
        + num2str(locRevenue(3))...
        + char(10)...
    + "Total: "...
        + num2str(totalDays)...
        + " days, $"...
        + num2str(totalRevenue);
disp(out);