%% FindMinMax.m
% Finds minimum and maximum values in a randomly-generated 2D array

clear;
clc;
close all;

%% Parameter and variable creation

nRow = 5;
nCol = 10;
nMax = 100;
minVal = nMax + 1;
maxVal = 0;
minPos = [0, 0];
maxPos = [0, 0];

randArr = randi(nMax, nRow, nCol);

%% Nested loops to search 2D array

for rowIndex = 1:nRow
    for colIndex = 1:nCol
        if randArr(rowIndex, colIndex) < minVal
            minVal = randArr(rowIndex, colIndex);
            minPos(1) = rowIndex;
            minPos(2) = colIndex;
        elseif randArr(rowIndex, colIndex) > maxVal
            maxVal = randArr(rowIndex, colIndex);
            maxPos(1) = rowIndex;
            maxPos(2) = colIndex;
        end
    end
end
disp("Generated a "...
    + "("...
    + num2str(nRow)...
    + " x "...
    + num2str(nCol)...
    + ")"...
    + " matrix of integers between 1 and "...
    + num2str(nMax)...
    + ".");
disp("Min value in the matrix was "...
    + num2str(minVal)...
    + ", which occurred at position ("...
    + num2str(minPos(1))...
    + ", "...
    + num2str(minPos(2))...
    + ").");
disp("Max value in the matrix was "...
    + num2str(maxVal)...
    + ", which occurred at position ("...
    + num2str(maxPos(1))...
    + ", "...
    + num2str(maxPos(2))...
    + ").");